# Generated by Django 3.1.3 on 2020-12-01 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201130_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='comments',
            new_name='commenting_users',
        ),
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.photo'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=255),
        ),
    ]
