# Generated by Django 3.1.3 on 2020-12-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201202_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='alt_text',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
